apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boot2crud-helmworkflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "boot2crud-helmworkflow.name" . }}
    helm.sh/chart: {{ include "boot2crud-helmworkflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "boot2crud-helmworkflow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "boot2crud-helmworkflow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPRING_DATA_MONGODB_URI
            # example value: mongodb://expoapp:s3cr3t@localhost:27017/expodb
            value: "mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@{{ .Values.mongo.name }}:27017/expodb"
            
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /swagger-ui.html?livenessProbe
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 3
#            periodSeconds: 5
#            timeoutSeconds: 2
#          readinessProbe:
#            httpGet:
#              path: /swagger-ui.html?readinessProbe
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 3
#            periodSeconds: 5
#            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
