## v1alpha2: RouteRule, DestinationPolicy, EgressRule, and (Kubernetes) Ingress
## v1alpha3: Gateway, VirtualService, DestinationRule, ServiceEntry

apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
    name: "default"
spec:
#    targets:
#    - name: "*"
    peers:
    - mtls:
        # alternative: STRICT(=doesn't allow nomtls-to-mtls ns communication!)
        mode: PERMISSIVE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
    name: "default"
spec:
    host: "*"
    trafficPolicy:
        tls:
            # ISTIO_MUTUAL = disallow mtls-to-nonmtls ns communication
            # DISABLE      = allows mtls-to-nomtls ns communication
            mode: DISABLE
