apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcpbin-gateway
spec:
  selector:
###    app.kubernetes.io/name: boot2crud-helmworkflow
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 27017
      name: mongo
      protocol: MONGO
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcpbin
spec:
  hosts:
  - "*"
  gateways:
  - tcpbin-gateway
  tcp:
  - match:
    - port: 27017
      #sourceSubnet: "0.0.0.0/0"
    route:
    - destination:
        port:
          number: 27017
        host: deployment-mongo
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-deployment-mongo
spec:
  hosts:
  - deployment.mongo
  ports:
  - number: 27017
    name: mongo
    protocol: MONGO
  location: MESH_INTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: deployment-mongo-destination
spec:
  host: deployment-mongo
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8080
      name: http8080
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 8088
      name: http8088
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 80
      name: http80
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9090
      name: http9090
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9153
      name: http9153
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 16686
      name: http16686
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9411
      name: http9411
      protocol: HTTP
    hosts:
    - "*"
 # - port:
 #     number: 443
 #     name: http443
 #     protocol: HTTPS
 #   hosts:
 #   - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway4istio
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8080
      name: http8080
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 8088
      name: http8088
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 80
      name: http80
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9090
      name: http9090
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9153
      name: http9153
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 16686
      name: http16686
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9411
      name: http9411
      protocol: HTTP
    hosts:
    - "*"
#  - port:
#      number: 443
#      name: http443
#      protocol: HTTPS
#    hosts:
#    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin4istio
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway4istio
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin4istio
