apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.mongo.name }}
    helm.sh/chart: "{{ .Values.mongo.name }}_chart"
    app.kubernetes.io/instance: "{{ .Values.mongo.name }}_release"
    app.kubernetes.io/managed-by: "{{ .Values.mongo.name }}_service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app.kubernetes.io/name: {{ .Values.mongo.name }}
    app.kubernetes.io/instance: "{{ .Values.mongo.name }}_release"
