apiVersion: v1
kind: Service
metadata:
  name: {{ include "boot2crud-helmworkflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "boot2crud-helmworkflow.name" . }}
    helm.sh/chart: {{ include "boot2crud-helmworkflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: serviceVersion1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "boot2crud-helmworkflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
